credentials:
  users:
    sampleuser:
      password: '123456'
      privileges:
        - permissions: [ read, write ]
          spaces: [ space ]
        - permissions: [ execute ]
          functions: [ get_bands_older_than ]
groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
                - uri: '127.0.0.1:3301'
app:
  file: './scripts/init.lua'